//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseManagement.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceEN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceEN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CourseManagement.Core.Resources.ResourceEN", typeof(ResourceEN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course code is duplicated!.
        /// </summary>
        internal static string EN_ValidateError_CourseCodeDuplicate {
            get {
                return ResourceManager.GetString("EN_ValidateError_CourseCodeDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course code is required!.
        /// </summary>
        internal static string EN_ValidateError_CourseCodeNotEmpty {
            get {
                return ResourceManager.GetString("EN_ValidateError_CourseCodeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course name is required!.
        /// </summary>
        internal static string EN_ValidateError_CourseNameNotEmpty {
            get {
                return ResourceManager.GetString("EN_ValidateError_CourseNameNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course not exists in system!.
        /// </summary>
        internal static string EN_ValidateError_CourseNotExists {
            get {
                return ResourceManager.GetString("EN_ValidateError_CourseNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee code and course code is not exists!.
        /// </summary>
        internal static string EN_ValidateError_EmployeeAndCourseNotExists {
            get {
                return ResourceManager.GetString("EN_ValidateError_EmployeeAndCourseNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee code is duplicated!.
        /// </summary>
        internal static string EN_ValidateError_EmployeeCodeDuplicate {
            get {
                return ResourceManager.GetString("EN_ValidateError_EmployeeCodeDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee code is required!.
        /// </summary>
        internal static string EN_ValidateError_EmployeeCodeNotEmpty {
            get {
                return ResourceManager.GetString("EN_ValidateError_EmployeeCodeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee name is required!.
        /// </summary>
        internal static string EN_ValidateError_EmployeeNameNotEmpty {
            get {
                return ResourceManager.GetString("EN_ValidateError_EmployeeNameNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee not exists!.
        /// </summary>
        internal static string EN_ValidateError_EmployeeNotExists {
            get {
                return ResourceManager.GetString("EN_ValidateError_EmployeeNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee has already registered for this course!.
        /// </summary>
        internal static string EN_ValidateError_EmployeeRegistedCourse {
            get {
                return ResourceManager.GetString("EN_ValidateError_EmployeeRegistedCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course code must have a length between 3 and 20 characters!.
        /// </summary>
        internal static string EN_ValidateError_InvalidCourseCodeLength {
            get {
                return ResourceManager.GetString("EN_ValidateError_InvalidCourseCodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth is invalid!.
        /// </summary>
        internal static string EN_ValidateError_InvalidDateOfBirth {
            get {
                return ResourceManager.GetString("EN_ValidateError_InvalidDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is invalid!.
        /// </summary>
        internal static string EN_ValidateError_InvalidEmail {
            get {
                return ResourceManager.GetString("EN_ValidateError_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee code must have a length between 3 and 20 characters!.
        /// </summary>
        internal static string EN_ValidateError_InvalidEmployeeCodeLength {
            get {
                return ResourceManager.GetString("EN_ValidateError_InvalidEmployeeCodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date must be after the start date!.
        /// </summary>
        internal static string EN_ValidateError_InvalidEndDate {
            get {
                return ResourceManager.GetString("EN_ValidateError_InvalidEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile phone is invalid!.
        /// </summary>
        internal static string EN_ValidateError_InvalidMobilePhone {
            get {
                return ResourceManager.GetString("EN_ValidateError_InvalidMobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date of the course must be after the current time!.
        /// </summary>
        internal static string EN_ValidateError_InvalidStartDate {
            get {
                return ResourceManager.GetString("EN_ValidateError_InvalidStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainer code must have a length between 3 and 20 characters!.
        /// </summary>
        internal static string EN_ValidateError_InvalidTrainerCodeLength {
            get {
                return ResourceManager.GetString("EN_ValidateError_InvalidTrainerCodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile phone already exists in the system!.
        /// </summary>
        internal static string EN_ValidateError_MobilePhoneDuplicate {
            get {
                return ResourceManager.GetString("EN_ValidateError_MobilePhoneDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainer code already exists in the system!.
        /// </summary>
        internal static string EN_ValidateError_TrainerCodeDuplicate {
            get {
                return ResourceManager.GetString("EN_ValidateError_TrainerCodeDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainer code is required!.
        /// </summary>
        internal static string EN_ValidateError_TrainerCodeNotEmpty {
            get {
                return ResourceManager.GetString("EN_ValidateError_TrainerCodeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainer name is required!.
        /// </summary>
        internal static string EN_ValidateError_TrainerNameNotEmpty {
            get {
                return ResourceManager.GetString("EN_ValidateError_TrainerNameNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password!.
        /// </summary>
        internal static string EN_WrongUsernameOrPassword {
            get {
                return ResourceManager.GetString("EN_WrongUsernameOrPassword", resourceCulture);
            }
        }
    }
}
