//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseManagement.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceVN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceVN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CourseManagement.Core.Resources.ResourceVN", typeof(ResourceVN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khóa học đã tồn tại trong hệ thống!.
        /// </summary>
        internal static string VN_ValidateError_CourseCodeDuplicate {
            get {
                return ResourceManager.GetString("VN_ValidateError_CourseCodeDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khóa học không được phép để trống!.
        /// </summary>
        internal static string VN_ValidateError_CourseCodeNotEmpty {
            get {
                return ResourceManager.GetString("VN_ValidateError_CourseCodeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên khóa học không được phép để trống!
        ///.
        /// </summary>
        internal static string VN_ValidateError_CourseNameNotEmpty {
            get {
                return ResourceManager.GetString("VN_ValidateError_CourseNameNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tồn tại khóa học này!.
        /// </summary>
        internal static string VN_ValidateError_CourseNotExists {
            get {
                return ResourceManager.GetString("VN_ValidateError_CourseNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên và mã khóa học chưa tồn tại!.
        /// </summary>
        internal static string VN_ValidateError_EmployeeAndCourseNotExists {
            get {
                return ResourceManager.GetString("VN_ValidateError_EmployeeAndCourseNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên đã tồn tại trong hệ thống!.
        /// </summary>
        internal static string VN_ValidateError_EmployeeCodeDuplicate {
            get {
                return ResourceManager.GetString("VN_ValidateError_EmployeeCodeDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không được phép để trống!.
        /// </summary>
        internal static string VN_ValidateError_EmployeeCodeNotEmpty {
            get {
                return ResourceManager.GetString("VN_ValidateError_EmployeeCodeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhân viên không được phép để trống!.
        /// </summary>
        internal static string VN_ValidateError_EmployeeNameNotEmpty {
            get {
                return ResourceManager.GetString("VN_ValidateError_EmployeeNameNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tồn tại nhân viên này!.
        /// </summary>
        internal static string VN_ValidateError_EmployeeNotExists {
            get {
                return ResourceManager.GetString("VN_ValidateError_EmployeeNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên đã đăng ký khóa học này rồi!.
        /// </summary>
        internal static string VN_ValidateError_EmployeeRegistedCourse {
            get {
                return ResourceManager.GetString("VN_ValidateError_EmployeeRegistedCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khóa học phải có độ dài từ 3 - 20 ký tự!.
        /// </summary>
        internal static string VN_ValidateError_InvalidCourseCodeLength {
            get {
                return ResourceManager.GetString("VN_ValidateError_InvalidCourseCodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh không hợp lệ, nhân viên chưa đủ 18 tuổi!.
        /// </summary>
        internal static string VN_ValidateError_InvalidDateOfBirth {
            get {
                return ResourceManager.GetString("VN_ValidateError_InvalidDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không đúng định dạng!.
        /// </summary>
        internal static string VN_ValidateError_InvalidEmail {
            get {
                return ResourceManager.GetString("VN_ValidateError_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên phải có độ dài từ 3-20 kí tự!.
        /// </summary>
        internal static string VN_ValidateError_InvalidEmployeeCodeLength {
            get {
                return ResourceManager.GetString("VN_ValidateError_InvalidEmployeeCodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày kết thúc phải sau ngày bắt đầu!.
        /// </summary>
        internal static string VN_ValidateError_InvalidEndDate {
            get {
                return ResourceManager.GetString("VN_ValidateError_InvalidEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại không đúng định dạng!.
        /// </summary>
        internal static string VN_ValidateError_InvalidMobilePhone {
            get {
                return ResourceManager.GetString("VN_ValidateError_InvalidMobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày bắt đầu khóa học phải sau thời điểm hiện tại!.
        /// </summary>
        internal static string VN_ValidateError_InvalidStartDate {
            get {
                return ResourceManager.GetString("VN_ValidateError_InvalidStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã giảng viên phải có độ dài từ 3-20 kí tự!.
        /// </summary>
        internal static string VN_ValidateError_InvalidTrainerCodeLength {
            get {
                return ResourceManager.GetString("VN_ValidateError_InvalidTrainerCodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại đã tồn tại trong hệ thống!.
        /// </summary>
        internal static string VN_ValidateError_MobilePhoneDuplicate {
            get {
                return ResourceManager.GetString("VN_ValidateError_MobilePhoneDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã giảng viên đã tồn tại trong hệ thống!.
        /// </summary>
        internal static string VN_ValidateError_TrainerCodeDuplicate {
            get {
                return ResourceManager.GetString("VN_ValidateError_TrainerCodeDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã giảng viên không được phép để trống!.
        /// </summary>
        internal static string VN_ValidateError_TrainerCodeNotEmpty {
            get {
                return ResourceManager.GetString("VN_ValidateError_TrainerCodeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên giảng viên không được phép để trống!.
        /// </summary>
        internal static string VN_ValidateError_TrainerNameNotEmpty {
            get {
                return ResourceManager.GetString("VN_ValidateError_TrainerNameNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản hoặc mật khẩu không chính xác!.
        /// </summary>
        internal static string VN_WrongUsernameOrPassword {
            get {
                return ResourceManager.GetString("VN_WrongUsernameOrPassword", resourceCulture);
            }
        }
    }
}
